# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: photo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bphoto.proto\"W\n\x0bRemotePhoto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x0b\n\x03src\x18\x05 \x01(\t\"\x1f\n\x10GetPhotosRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"/\n\x10GetPhotoResponse\x12\x1b\n\x05photo\x18\x01 \x01(\x0b\x32\x0c.RemotePhoto\"O\n\x0b\x42inaryPhoto\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\"1\n\x12UploadPhotoRequest\x12\x1b\n\x05photo\x18\x01 \x01(\x0b\x32\x0c.BinaryPhoto\"(\n\x14UploadPhotosResponse\x12\x10\n\x08uploaded\x18\x01 \x01(\x08\x32\x85\x01\n\x0cPhotoService\x12\x35\n\tGetPhotos\x12\x11.GetPhotosRequest\x1a\x11.GetPhotoResponse\"\x00\x30\x01\x12>\n\x0cUploadPhotos\x12\x13.UploadPhotoRequest\x1a\x15.UploadPhotosResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REMOTEPHOTO']._serialized_start=15
  _globals['_REMOTEPHOTO']._serialized_end=102
  _globals['_GETPHOTOSREQUEST']._serialized_start=104
  _globals['_GETPHOTOSREQUEST']._serialized_end=135
  _globals['_GETPHOTORESPONSE']._serialized_start=137
  _globals['_GETPHOTORESPONSE']._serialized_end=184
  _globals['_BINARYPHOTO']._serialized_start=186
  _globals['_BINARYPHOTO']._serialized_end=265
  _globals['_UPLOADPHOTOREQUEST']._serialized_start=267
  _globals['_UPLOADPHOTOREQUEST']._serialized_end=316
  _globals['_UPLOADPHOTOSRESPONSE']._serialized_start=318
  _globals['_UPLOADPHOTOSRESPONSE']._serialized_end=358
  _globals['_PHOTOSERVICE']._serialized_start=361
  _globals['_PHOTOSERVICE']._serialized_end=494
# @@protoc_insertion_point(module_scope)
